POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json
x-api-key: QC5CzhMZoXtlQuzYjeeCBJmS4skbZoHA

{
    "email": "admin@gmail.com",
    "password": "!Qaz123456"
}
###
POST http://localhost:8080/api/v1/auth/refresh-token
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZDE1OThmMmE3ZGRjNzlhM2Q0YjdjNCIsImVtYWlsIjoiZGV2MjQyMzJAZ21haWwuY29tIiwicm9sZXMiOlsic3RhZmYiXSwiaWF0IjoxNzU4NjM0MDIxLCJleHAiOjE3NjEyMjYwMjF9.pBY7NkvmvK57e3AI2uw2ekjn-lO8KxoHpZtqNJl1nK8

# {
#     "email": "dev24232@gmail.com",
#     "password": "!Qaz123456"
# }