### users routes test
# {
#   "_id": {
#     "$oid": "68d2a822df1a89ef5c5cbec4"
#   },
#   "roles": [
#     "superadmin"
#   ],
#   "password": "$2b$10$OPgwlZtavdy/tgwBh9ntauqu7vT2BR7q9Ec516mLX862sL/UisnOC",
#   "email": "admin159753@gmail.com",
#   "first_name": "admin",
#   "last_name": "super",
#   "__v": 0
# }
### 200
POST http://localhost:9000/api/v1/auth/login
Content-Type: application/json
x-api-key: QC5CzhMZoXtlQuzYjeeCBJmS4skbZoHA

{
    "email": "admin@gmail.com",
    "password": "!Qaz123456"
}
### 200
POST http://localhost:8080/api/v1/auth/refresh-token
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZDRkZWJiMTk5MjM5ZGQ0ZmY0M2M3ZiIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZXMiOlsic3VwZXJhZG1pbiJdLCJpYXQiOjE3NTkxMzg1NzMsImV4cCI6MTc1OTc0MzM3M30.XYEL9sEuKcc6fIZ3Kd8ucYEzxE_z60X9N8IlRgdsEik
x-api-key: QC5CzhMZoXtlQuzYjeeCBJmS4skbZoHA
### 401
get http://localhost:9000/api/v1/categories
x-api-key: QC5CzhMZoXtlQuzYjeeCBJmS4skbZoHA
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZDRkZWJiMTk5MjM5ZGQ0ZmY0M2M3ZiIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZXMiOlsic3VwZXJhZG1pbiJdLCJpYXQiOjE3NTkxMzg1NzMsImV4cCI6MTc1OTc0MzM3M30.XYEL9sEuKcc6fIZ3Kd8ucYEzxE_z60X9N8IlRgdsEik
x-api-key: QC5CzhMZoXtlQuzYjeeCBJmS4skbZoHA
### 200 / 401
get http://localhost:8080/api/v1/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZDJhODIyZGYxYTg5ZWY1YzVjYmVjNCIsImVtYWlsIjoiYWRtaW4xNTk3NTNAZ21haWwuY29tIiwicm9sZXMiOlsic3VwZXJhZG1pbiJdLCJpYXQiOjE3NTg3MTMxNDQsImV4cCI6MTc1OTMxNzk0NH0.JLp7Dhc2tT_eSm4TMOgx9z8AaR6VGpaTVtsQK-2NRqI
x-api-key: QC5CzhMZoXtlQuzYjeeCBJmS4skbZoHA
### 200
get http://localhost:8080/api/v1/products
x-api-key: QC5CzhMZoXtlQuzYjeeCBJmS4skbZoHA
### products routes test
get http://localhost:8080/api/v1/products
x-api-key: QC5CzhMZoXtlQuzYjeeCBJmS4skbZoHA
###
POST http://localhost:8080/api/v1/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZDJhODIyZGYxYTg5ZWY1YzVjYmVjNCIsImVtYWlsIjoiYWRtaW4xNTk3NTNAZ21haWwuY29tIiwicm9sZXMiOlsic3VwZXJhZG1pbiJdLCJpYXQiOjE3NTg3MTMxNDQsImV4cCI6MTc1OTMxNzk0NH0.JLp7Dhc2tT_eSm4TMOgx9z8AaR6VGpaTVtsQK-2NRqI
x-api-key: QC5CzhMZoXtlQuzYjeeCBJmS4skbZoHA

{
  "product_name": "Adidas Ultraboost7",
  "category_id": "68d39fa57ca8664f02e98ef9",
  "brand_id": "68d39fa57ca8664f02e98ef4",
  "description": "nfjdknskf",
  "slug": "adidas-ultraboost6",
  "sku": "ADU001SKALFJSKAFSAL",
  "price": 150,
  "stock": 30,
  "image_url": "https://example.com/adidas-ultraboost.jpg",
  "variant": [
    "white",
    "black"
  ],
  "isDeleted": false
}
### get profile
POST http://localhost:8080/api/v1/auth/get-profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZDRkZWJiMTk5MjM5ZGQ0ZmY0M2M3ZiIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZXMiOlsic3VwZXJhZG1pbiJdLCJpYXQiOjE3NTg4NzE4OTIsImV4cCI6MTc1OTQ3NjY5Mn0.cIZhPpq4b0haX7oSbw0gdkjmowj18xsltwXhMP9y6zY
x-api-key: QC5CzhMZoXtlQuzYjeeCBJmS4skbZoHA