### users routes test
# {
#   "_id": {
#     "$oid": "68d2a822df1a89ef5c5cbec4"
#   },
#   "roles": [
#     "admin"
#   ],
#   "password": "$2b$10$OPgwlZtavdy/tgwBh9ntauqu7vT2BR7q9Ec516mLX862sL/UisnOC",
#   "email": "admin159753@gmail.com",
#   "first_name": "admin",
#   "last_name": "super",
#   "__v": 0
# }
### 200
POST http://localhost:9000/api/v1/auth/login
Content-Type: application/json
x-api-key: 6b92W0lULyoh1Fz5mXCkPdtD6x0NzMsa

{
    "email": "staff@gmail.com",
    "password": "!Qaz123456"
}
### 200
POST http://localhost:8080/api/v1/auth/refresh-token
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZDJhODIyZGYxYTg5ZWY1YzVjYmVjNCIsImVtYWlsIjoiYWRtaW4xNTk3NTNAZ21haWwuY29tIiwicm9sZXMiOlsic3VwZXJhZG1pbiJdLCJpYXQiOjE3NTg3MTMxNDQsImV4cCI6MTc1OTMxNzk0NH0.JLp7Dhc2tT_eSm4TMOgx9z8AaR6VGpaTVtsQK-2NRqI
x-api-key: QC5CzhMZoXtlQuzYjeeCBJmS4skbZoHA
### 401
get http://localhost:9000/api/v1/products/slug/iphone-16-pro-max
x-api-key: QC5CzhMZoXtlQuzYjeeCBJmS4skbZoHA
### 200 / 401
get http://localhost:9000/api/v1/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZDJhODIyZGYxYTg5ZWY1YzVjYmVjNCIsImVtYWlsIjoiYWRtaW4xNTk3NTNAZ21haWwuY29tIiwicm9sZXMiOlsic3VwZXJhZG1pbiJdLCJpYXQiOjE3NTg3MTMxNDQsImV4cCI6MTc1OTMxNzk0NH0.JLp7Dhc2tT_eSm4TMOgx9z8AaR6VGpaTVtsQK-2NRqI
x-api-key: QC5CzhMZoXtlQuzYjeeCBJmS4skbZoHA
### 200
get http://localhost:9000/api/v1/brands
x-api-key: 6b92W0lULyoh1Fz5mXCkPdtD6x0NzMsa
### products routes test
GET http://localhost:9000/api/v1/orders
x-api-key: QC5CzhMZoXtlQuzYjeeCBJmS4skbZoHA
###
POST http://localhost:8080/api/v1/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZDJhODIyZGYxYTg5ZWY1YzVjYmVjNCIsImVtYWlsIjoiYWRtaW4xNTk3NTNAZ21haWwuY29tIiwicm9sZXMiOlsic3VwZXJhZG1pbiJdLCJpYXQiOjE3NTg3MTMxNDQsImV4cCI6MTc1OTMxNzk0NH0.JLp7Dhc2tT_eSm4TMOgx9z8AaR6VGpaTVtsQK-2NRqI
x-api-key: QC5CzhMZoXtlQuzYjeeCBJmS4skbZoHA

{
  "product_name": "Adidas Ultraboost7",
  "category_id": "68d39fa57ca8664f02e98ef9",
  "brand_id": "68d39fa57ca8664f02e98ef4",
  "description": "nfjdknskf",
  "slug": "adidas-ultraboost6",
  "sku": "ADU001SKALFJSKAFSAL",
  "price": 150,
  "stock": 30,
  "image_url": "https://example.com/adidas-ultraboost.jpg",
  "variant": [
    "white",
    "black"
  ],
  "isDeleted": false
}
### customers routes test
GET http://localhost:9000/api/v1/products/home/6878dd70c4303577d8af6fa0?limit=5
###
PUT http://localhost:9000/api/v1/orders/68dd578b168463065d4106dc
Content-Type: application/json
x-api-key: QC5CzhMZoXtlQuzYjeeCBJmS4skbZoHA
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZDJhODIyZGYxYTg5ZWY1YzVjYmVjNCIsImVtYWlsIjoic3RhZmZAZ21haWwuY29tIiwicm9sZXMiOlsic3RhZmYiXSwiaWF0IjoxNzU5NDkwMTkwLCJleHAiOjE3NjAwOTQ5OTB9.DaJx9neZn5sRNz1Vz9UTd6ioyrHG-_qL1BSnZayZJtI

{
    "staff": "68d2a822df1a89ef5c5cbec4",
    "order_status": "4"
}

###
GET http://localhost:9000/api/v1/products/68da5fc9d4042eb3781ab884
x-api-key: 6b92W0lULyoh1Fz5mXCkPdtD6x0NzMsa

###
POST http://localhost:9000/api/v1/customers/login
Content-Type: application/json
x-api-key: 6b92W0lULyoh1Fz5mXCkPdtD6x0NzMsa

{
    "email": "john@gmail.com",
    "password": "!Qaz123456"
}