# require using json in app.ts to parse
POST http://localhost:8080/api/v1/categories
Content-Type: application/json

{
    "name": "New Category",
    "description": "description",
    "slug": "slug"
}
###
put http://localhost:8080/api/v1/categories/68ce37c4aa4896602f152368
Content-Type: application/json

{
    "name": "New Category"
}
###
DELETE http://localhost:8080/api/v1/categories/3
###
get http://localhost:8080/api/v1/shipments
###
get http://localhost:8080/api/v1/products?page=1